### ISSUE TITLE
srcchk excluded because of unmet requirements

### ISSUE THREAD

**Issue by Phylloxera** [ncbi/ncbi-cxx-toolkit-public#11]
I'm trying to rebuild srcchk and possibly vecscreen. I have sqlite3 installed. 
`which sqlite3` `/usr/bin/sqlite3`
`./cmake-configure --with-projects="app"` from ncbi_cxx--25_2_0 from the NCBI ftp site fails to detect several requirements: 
`(/home/aaron/ncbi_cxx--25_2_0/src/app/srcchk) is excluded because of unmet requirements: BerkeleyDB;NGHTTP2;SQLITE3;UV`. 
In contrast, ncbi-cxx-toolkit-public-release-28.0.8 only fails to detect SQLITE3. 
I'm running Ubuntu Jammy on a VM.

**Comment by ucko** [comment]
The build system mostly looks for development libraries, not command-line tools; sorry if that was unclear.  Please try running
```
sudo apt install libdb-dev libnghttp2-dev libsqlite3-dev libuv1-dev
```

Thanks for your interest, and apologies again for any confusion.
-- a fellow Aaron
