### ISSUE TITLE
build specific tool

### ISSUE THREAD

**Issue by Smeds** [ncbi/ncbi-cxx-toolkit-public#12]
Is it possible to limit the build step to specific tools? Let say I only want to build WindowMasker and not all tools which take a lot of time.

**Comment by gouriano** [comment]
Please see [here](https://ncbi.github.io/cxx-toolkit/pages/ch_cmconfig#ch_cmconfig._Configure)

**Comment by vakatov** [comment]
Looks like this helped, so -- closing this issue as completed. Feel free to reopen if need more info.
