### ISSUE TITLE
error: no declaration matches ‘std::wstring ncbi::CStringUTF8_DEPRECATED::AsUnicode(const wchar_t*) const’

### ISSUE THREAD

**Issue by XuyingZhu** [ncbi/ncbi-cxx-toolkit-public#14]
Dear NCBI c++ toolkit team,

Thanks for such an amazing tool. However, I had a problem when I used the make command to download NCBI c++ toolkit 28.0.11.

The error message is as follows:

/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/include/corelib/impl/stringutf8_deprecated.inl:167:16: error: no declaration matches ‘std::wstring ncbi::CStringUTF8_DEPRECATED::AsUnicode(const wchar_t*) const’
  167 | inline wstring CStringUTF8_DEPRECATED::AsUnicode(const wchar_t* substitute_on_error) const

Would you please give some advice on dealing with the sequences to solve this problem? Thank you, and I am looking forward to your recent reply!

Best wishes,
Xuying Zhu

**Comment by vakatov** [comment]
Hi, how did you configure the C++ Toolkit tree? What's your OS? What's the compiler command line?

**Comment by XuyingZhu** [comment]
Thank you for your reply!

My configure command is `env CXX=/share/home/zhuyy/software/ncbi-cxx-toolkit/bin/gcc ./configure`. 

My OS is Linux. 

After configure command, I used the command 

`cd /share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/GCC1420-DebugMT64/build && /share/home/zhuyy/anaconda3/bin/make all_r`, 

as the recommendation at the end of the configuration:
`To build everything:  cd /share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/GCC1420-DebugMT64/build && /share/home/zhuyy/anaconda3/bin/make all_r
or simply run /share/home/zhuyy/anaconda3/bin/make in the current directory


******* CONFIGURATION SUCCESSFUL *******
`

**Comment by vakatov** [comment]
This looks like an oversight in our code. Can you go into ncbi-cxx-toolkit-28.0.11/include/corelib/impl/stringutf8_deprecated.inl, line and surround the function's code with the following preprocessor conditional:

#if defined(HAVE_WSTRING)
inline wstring CStringUTF8_DEPRECATED::AsUnicode(const wchar_t* substitute_on_error) const
{
    return CUtf8::AsBasicString<wchar_t>(*this,substitute_on_error,CUtf8::eNoValidate);
}
#endif

**Comment by ucko** [comment]
That said, I'm surprised that this change is necessary.  Could you please attach `/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/GCC1420-DebugMT64/status/config.log`  to help us determine why `HAVE_WSTRING` isn't defined for you?  Thanks!

**Comment by XuyingZhu** [comment]
[config.log](https://github.com/user-attachments/files/18070627/config.log)
Thank you for your reply! The config.log was attached with this commit.

**Comment by XuyingZhu** [comment]
> This looks like an oversight in our code. Can you go into ncbi-cxx-toolkit-28.0.11/include/corelib/impl/stringutf8_deprecated.inl, line and surround the function's code with the following preprocessor conditional:
> 
> #if defined(HAVE_WSTRING) inline wstring CStringUTF8_DEPRECATED::AsUnicode(const wchar_t* substitute_on_error) const { return CUtf8::AsBasicString<wchar_t>(*this,substitute_on_error,CUtf8::eNoValidate); } #endif

Thank you for your reply! I tried to add the code but still failed. The config.log was attached in my other commit. I hope it can help to solve the problem.

**Comment by vakatov** [comment]
What was the error?

FWIW, there was yet another error in the same file, which was fixed like this:

**Comment by ucko** [comment]
Got it, thanks!  Looks like your alternative compiler setup isn't picking up the right version of `libstdc++`, yielding trouble in various spots, e.g.
```
configure:13786: checking for wstring
[...]
/tmp/ccqUZBW1.o: In function `main':
/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/conftest.cpp:46: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string()'
/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/conftest.cpp:46: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string()'
/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/conftest.cpp:46: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::find_first_of(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, unsigned long) const'
/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/conftest.cpp:49: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
/share/home/zhuyy/software/ncbi-cxx-toolkit/ncbi-cxx-toolkit-28.0.11/conftest.cpp:49: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_string()'
collect2: error: ld returned 1 exit status
```
and
```
configure:22943: checking for Boost.Chrono
[...]
/usr/bin/ld: /tmp/ccyvbYo6.o: undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
/share/home/zhuyy/anaconda3/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
(The public portion of the Toolkit doesn't use Boost.Chrono, but that error doesn't bode well.)

Fully troubleshooting your setup is out of scope for us, sorry; please try to take it from here yourself.
