### ISSUE TITLE
configure: error: --with-gui:  GUI sources are missing

### ISSUE THREAD

**Issue by trappedinspacetime** [ncbi/ncbi-cxx-toolkit-public#3]
Hi,

When I attempt to build it with `gbench` :

          ./configure  --without-debug --with-gbench 

I get :

            configure: error: --with-gui:  GUI sources are missing
            
What should I do?

**Comment by gouriano** [comment]
GUI sources are not included here. You cannot do anything

**Comment by trappedinspacetime** [comment]
Can I add them manually?

**Comment by vakatov** [comment]
What are you trying to build? E.g. if it's GBENCH, then I believe they have their own releases (and, surely, pre-built binaries).

**Comment by gouriano** [comment]
Sure you can. But I have no idea if it will work or not. As far as I understand it, gbench is much bigger than 'GUI'

**Comment by ucko** [comment]
You can find full gbench sources (along with prebuilt binaries for popular platforms) at https://ftp.ncbi.nlm.nih.gov/toolbox/gbench/, but I wouldn't recommend trying to mix and match subtrees.

Sorry for any confusion - the trees share build-system logic that alas cannot readily present options conditionally.  (On a related note, the build system checks for some third-party libraries that are only of interest to gbench and/or internal projects; it treats them all as optional, of course.)

**Comment by trappedinspacetime** [comment]
@ucko Thank you for the suggestion. Yes, it's installed including `libgtk2.0-dev  libgtk-3-dev libgtk-4-dev`

**Comment by ucko** [comment]
Ah, the build system doesn't properly account for the possibility of wxWidgets installations built against GTK 3 or newer.  I'll look into fixing that; thanks for the report!

Meanwhile, AFAIK, it's specifically GTK 3 that's in play here; please try reinvoking the configure script with the additional argument

CPPFLAGS="$(pkg-config gtk+-3.0 --cflags)"

This workaround will have a somewhat broader impact than necessary, but that shouldn't be a problem.

**Comment by trappedinspacetime** [comment]
@ucko I think your your `CPPFLAGS` trick worked. Prior to `./configure --without-debug --with-gbench`  I did `export CPPFLAGS="$(pkg-config gtk+-3.0 --cflags)"`. I didn't get `gtk/gtk.h` error but I got another one:

          /home/***/Downloads/gbench-3.8.1/src/gui/widgets/wx/dock_hint_frame.cpp:87:47: error: ‘GtkWidget’ {aka ‘struct _GtkWidget’} has no member named ‘window’
             87 |     gdk_window_shape_combine_region(m_widget->window, region.GetRegion(), 0, 0);

**Comment by ucko** [comment]
Ah, yeah, that's progress; it looks like some code changes are also in order to accommodate GTK 3, though.  With any luck, they'll be small and formal.

**Comment by trappedinspacetime** [comment]
I installed all the packages required within [gbench-src-3.8.1.tar.gz](https://ftp.ncbi.nlm.nih.gov/toolbox/gbench/ver-3.8.1/gbench-src-3.8.1.tar.gz) in `ubuntu18_install_dev_pkgs.sh`. It appears that `wxwidgets` uses `libgtk2.0-dev` as it's mentioned in `ubuntu18_install_dev_pkgs.sh` file. So, I tried :

       export CPPFLAGS="$(pkg-config gtk+-2.0 --cflags)"

This time I encountered another error:

      error: cannot convert ‘cairo_region_t*’ {aka ‘_cairo_region*’} to ‘const GdkRegion*’ {aka ‘const _GdkRegion*’

**Comment by trappedinspacetime** [comment]
@ucko I am grateful to your help. I did what you said. Your last suggestion worked. I didn't encounter `cairo` error. 
I hit another error now:

      /home/***/Downloads/gbench-3.8.1/src/gui/widgets/feedback/dump_sysinfo.cpp: In static member function ‘static void ncbi::CDumpSysInfo::DumpSystemInfo(ncbi::CNcbiOstream&)’:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:39:75: error: expected primary-expression before ‘)’ token

**Comment by ucko** [comment]
So I see.  It looks like substituting wxGetX11Display() for GDK_DISPLAY() on line 245 of ~/ Downloads/gbench-3.8.1/src/gui/widgets/feedback/dump_sysinfo.cpp should take care of that one.

**Comment by ucko** [comment]
Please try explicitly qualifying IsEmpty with wxItemContainer:

    bool is_empty = m_ProductCtrl->wxItemContainer::IsEmpty();

IsListEmpty comes from wxWidgets 3.1.x, which a lot of distributions didn't package because they weren't officially stable releases.

I do apologize for all the back-and-forth; I have been running my own testing, but for various reasons haven't gotten much further yet.  That said, I did spot one other tweak you'll need to make to that library for compatibility with wxWidgets 3.0.x, namely conditionalizing the use of a custom icon in CMacroEditor::DisplayNotice at the bottom of macro_editor.cpp:

...
    if (w) {
        CMacroFlowEditor* frame = dynamic_cast<CMacroFlowEditor*>(w);
#if wxCHECK_VERSION(3, 1, 0)
                    wxIcon icon;
                    icon.CopyFromBitmap(frame->GetPlusBitmap());
                    notice.SetIcon(icon);
#endif
    }
...

AFAICT, that code was relying on wholly new functionality, but doing without it if necessary should be OK.

**Comment by trappedinspacetime** [comment]
@ucko You no need to apologize. I feel sorry since I come up with new errors.

New error I encounttered is:

      /home/***/Downloads/gbench-3.8.1/src/gui/widgets/seq_graphic/track_list_ctrl.cpp:93:39: error: no matching function for call to ‘wxImageList::GetSize()’
       93 |     wxSize size = m_ImageList->GetSize();

I post it because I wanted to inform you; it may help you. 

I have no urgent demand for compilation. 
Thank you for your help.

**Comment by vakatov** [comment]
Hopefully it's all good now. If not feel free to reopen.
