### ISSUE TITLE
GCC 13 complains of missing headers

### ISSUE THREAD

**Issue by mys721tx** [ncbi/ncbi-cxx-toolkit-public#6]
Since GCC 13 changed the [C standard library dependencies](https://gcc.gnu.org/gcc-13/porting_to.html), some headers need to be explicitly included.

As of 28b1a1fb, blast+ 2.14.0 and by extension the c++ toolkit cannot be compiled on GCC 13.

```
/home/mys_721tx/WorkSpace/ncbi-cxx-toolkit-public/include/util/impl/compile_time_bits.hpp:685:25: error: ‘uintptr_t’ is not a member of ‘std’
  685 |             return std::uintptr_t(m_backend.get_index()) % std::hardware_constructive_interference_size;
      |                         ^~~~~~~~~
/home/mys_721tx/WorkSpace/ncbi-cxx-toolkit-public/include/util/impl/compile_time_bits.hpp:86:1: note: ‘std::uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   85 | #include "ct_string_cxx17.hpp"
  +++ |+#include <cstdint>
   86 | 
make[3]: Leaving directory '/home/mys_721tx/WorkSpace/ncbi-cxx-toolkit-public/GCC1311-DebugMTDLL64/build/util'
make[3]: *** [/home/mys_721tx/WorkSpace/ncbi-cxx-toolkit-public/GCC1311-DebugMTDLL64/build/Makefile.rules:103: multipattern_search.o] Error 1
```

**Comment by mys721tx** [comment]
Looks like `include/util/impl/compile_time_bits.hpp` is the only file using `std::uintptr_t` and adding `#include <cstdint>` to it solves the problem. If needed, I can draft a patch.

**Comment by vakatov** [comment]
Sure. - Thanks!

**Comment by gouriano** [comment]
Yes, adding cstdint into compile_time_bits.hpp seems like a best fix. I have added it already. it will take some time to come to github.

**Comment by mys721tx** [comment]
My NLM Case #: CAS-1128678-W3P5C4  for folks on the back end.

**Comment by vakatov** [comment]
The fix is now in GitHub: https://github.com/ncbi/ncbi-cxx-toolkit-public/commit/9c49d6c96b656c7ed605bc7a9bbd9cf5521d3e1e
